### ISSUE TITLE
文章中にドキュメントの復元をした旨の追記をお願いします。

### ISSUE THREAD

**Issue by him0** [namuyan/NEM_API_DOC#1]
@namuyan nemmanual.net からのリンクをこちらの markdown にしようかと思うのですが、ただ単に復元したものをリンクしてしまうと、namuyan さんに文句が来るといけないので、削除されたので、復元したものであることの追記をお願いしたいです。よろしくおねがいします。

**Comment by namuyan** [comment]
Done
